### PR TITLE
sparse-checkout: don't update sparse-checkout file on error

### LINKED ISSUE #198: Sparse-checkout builtin is not atomic
The `git sparse-checkout set` subcommand updates the `sparse-checkout` then tries a `git read-tree -mu HEAD`. If there are conflicts in the files being added or removed, then the `read-tree` will fail. However, the sparse-checkout file is still updated, which will lead to a surprise when eventually the checkout succeeds.

Make the `set` subcommand more atomic by backing up the sparse-checkout file and reverting the changes on a failed update.

### PR DESCRIPTION
**Pull request by derrickstolee**
If the index has an unstaged change in a file that will be dropped
by a change to the sparse-checkout file, then the index update
will fail. If this happens during 'git sparse-checkout set', then
the entire command will fail. However, the sparse-checkout file is
still updated, so the working directory is in a half-finished state.

Update the sparse-checkout builtin to run `unpack_trees()`
directly instead of through an external `git read-tree` process.
While doing so, allow passing a set of patterns, so we can
validate the patterns before trying to write to the sparse-checkout
file.

Also, write sparse-checkout under a .lock and take the
sparse-checkout lock around the unpack_trees() check.

Resolves #198.

### CODE REVIEW

File: builtin/sparse-checkout.c [hunk 1]
```diff
@@ -259,9 +259,21 @@ static void write_cone_to_file(FILE *fp, struct pattern_list *pl)
...
 {
 	char *sparse_filename;
+	struct strbuf backup_filename = STRBUF_INIT;
 	FILE *fp;
+	int sparse_existed;
+	int result;
 
 	sparse_filename = get_sparse_checkout_filename();
+	strbuf_addstr(&backup_filename, sparse_filename);
+	strbuf_addstr(&backup_filename, ".backup");
```
Comment (kewillford) [inline builtin/sparse-checkout.c]: Maybe this is overkill but should we be using the `.lock` mechanisms in git to write the change to the `.lock` file and delete that on failure or rename on success?

Comment (kewillford) [reply builtin/sparse-checkout.c]: Also thinking about this a little and do we need the protection of the `.lock` to prevent 2 `sparse-checkout` commands from running at the same time?

Comment (derrickstolee) [reply builtin/sparse-checkout.c]: You are probably right about the `.lock` file, but that won't solve the situation here: we need to commit the `.lock` file before the update can work on the new data.

However, I do wonder if we can do something more clever: we have a `struct pattern_list`. Can we try running `clear_ce_flags()` based on this list and get an error from that instead? I will investigate.

File: builtin/sparse-checkout.c [hunk 2]
```diff
@@ -285,8 +339,8 @@ static void strbuf_to_cone_pattern(struct strbuf *line, struct pattern_list *pl)
 	if (!line->len)
 		return;
 
-	if (line->buf[0] == '/')
-		strbuf_remove(line, 0, 1);
+	if (line->buf[0] != '/')
+		strbuf_insert(line, 0, "/", 1);
 
 	if (!line->len)
```
Comment (derrickstolee) [inline builtin/sparse-checkout.c]: remove this now that it is useless.

File: builtin/sparse-checkout.c [hunk 3]
```diff
@@ -343,11 +399,11 @@ static int sparse_checkout_set(int argc, const char **argv, const char *prefix)
 			while (!strbuf_getline(&line, stdin)) {
 				size_t len;
 				char *buf = strbuf_detach(&line, &len);
-				add_pattern(buf, buf, len, &pl, 0);
+				add_pattern(buf, empty_base, 0, &pl, 0);
 			}
 		} else {
 			for (i = 0; i < argc; i++)
-				add_pattern(argv[i], argv[i], strlen(argv[i]), &pl, 0);
+				add_pattern(argv[i], empty_base,0, &pl, 0);
```
Comment (derrickstolee) [inline builtin/sparse-checkout.c]: nit: whitespace

File: builtin/sparse-checkout.c [hunk 4]
```diff
@@ -60,18 +65,53 @@ static int sparse_checkout_list(int argc, const char **argv)
...
+	struct lock_file lock_file = LOCK_INIT;
+	struct object_id oid;
+	struct tree *tree;
+	struct tree_desc t;
+	struct repository *r = the_repository;
 
-	if (run_command_v_opt(argv.argv, RUN_GIT_CMD)) {
-		error(_("failed to update index with new sparse-checkout paths"));
-		result = 1;
+	if (repo_read_index_unmerged(r))
```
Comment (wilbaker) [inline builtin/sparse-checkout.c]: > If the index has an unstaged change in a file that will be dropped
by a change to the sparse-checkout file, then the index update
will fail. 

For my own understanding, what happens to untracked files that are outside of the new cone?  Are they left in place or deleted?

File: dir.h [hunk 5]
```diff
@@ -71,6 +71,7 @@ struct pattern_list {
 	 * excludes array above. If non-zero, that check succeeded.
 	 */
 	unsigned use_cone_patterns;
+	unsigned full_cone;
```
Comment (wilbaker) [inline dir.h:74]: >However, we instead need to handle the case where that second
line does not exist. Due to the MUSTBEDIR and NEGATIVE flags, the
second pattern becomes "/*".
>
>Create a new option in struct pattern_list to store this "full
cone" mode. When we see the "/*" pattern with no flags, we toggle
full_cone to on. If we later see "/*" pattern with MUSTBEDIR and
NEGATIVE flags, then turn full_cone off.

For my own understanding, are these flags set when the file is parsed?

File: dir.c [hunk 6]
```diff
@@ -622,8 +622,17 @@ static void add_pattern_to_hashsets(struct pattern_list *pl, struct path_pattern
 	if (!pl->use_cone_patterns)
 		return;
 
-	if (!strcmp(given->pattern, "/*"))
+	if (given->flags & PATTERN_FLAG_NEGATIVE &&
+	    given->flags & PATTERN_FLAG_MUSTBEDIR &&
```
Comment (wilbaker) [inline dir.c:626]: Under what circumstances would only one of `PATTERN_FLAG_NEGATIVE` and `PATTERN_FLAG_MUSTBEDIR` be set?

**Review by wilbaker — COMMENTED** [review]
I left a few questions to help with my understanding of this code.

File: builtin/sparse-checkout.c (hunk 4 above)
Comment (derrickstolee) [reply builtin/sparse-checkout.c]: From my testing, it looks like untracked/non-ignored files remain. Everything else in the parent directory will be deleted.

File: dir.h (hunk 5 above)
Comment (derrickstolee) [reply dir.h:74]: Yes, this is part of the `parse_path_pattern()` method in `dir.c`, which is called by `add_pattern()` inside `add_patterns_from_buffer()`.

Comment (derrickstolee) [reply dir.h:74]: That method also strips out the tail `/` for directories (`MUSTBEDIR` flag) and the preceding `!` for negations (`NEGATIVE` flag).

File: dir.c (hunk 6 above)
Comment (derrickstolee) [reply dir.c:626]:
```
| Pattern        | Flags              |
|----------------+--------------------|
| /A/B/f.txt     | (none)             |
|----------------+--------------------|
| !/A/B/f.txt    | NEGATIVE           |
|----------------+--------------------|
| /A/B/          | MUSTBEDIR          |
|----------------+--------------------|
| !/A/B/         | MUSTBEDIR|NEGATIVE |
|----------------+--------------------|
```

**Comment by derrickstolee** [comment]
Ping on this one. I adapted these commits into [v3 of the sparse-checkout series](https://public-inbox.org/git/pull.316.v3.git.gitgitgadget@gmail.com/T/#u) which went upstream yesterday. I expect to need a re-roll due to clashes with some hashmap changes.

cc: @kewillford @wilbaker

File: dir.c [hunk 7]
```diff
@@ -1285,6 +1294,9 @@ enum pattern_match_result path_matches_pattern_list(
 		return UNDECIDED;
 	}
 
+	if (pl->full_cone)
+		return MATCHED;
```
Comment (kewillford) [inline dir.c:1298]: Why is the `MATCHED` and not `MATCHED_RECURSIVE`?

File: dir.c [hunk 8]
```diff
@@ -622,8 +622,17 @@ static void add_pattern_to_hashsets(struct pattern_list *pl, struct path_pattern
 	if (!pl->use_cone_patterns)
 		return;
 
-	if (!strcmp(given->pattern, "/*"))
+	if (given->flags & PATTERN_FLAG_NEGATIVE &&
+	    given->flags & PATTERN_FLAG_MUSTBEDIR &&
+	    !strcmp(given->pattern, "/*")) {
+		pl->full_cone = 0;
```
Comment (wilbaker) [inline dir.c:628]: Apologies if we already discussed this (I'm having trouble finding it if we did), but is there somewhere that git enforces that the sparse-checkout file is "valid", or are the entries guaranteed to be in a particular order?

I ask because I'm wondering if after setting `pl->full_cone = 0` here we might read an entry that sets it to 1 below (or vice-versa).  Is that the expected behavior?

File: dir.c [hunk 9]
```diff
@@ -622,8 +622,17 @@ static void add_pattern_to_hashsets(struct pattern_list *pl, struct path_pattern
...
 		return;
+	}
+
+	if (!given->flags && !strcmp(given->pattern, "/*")) {
+		pl->full_cone = 1;
```
Comment (kewillford) [inline dir.c:633]: I'm a little confused on what `full_cone` means.  Will you explain the intent of the flag?

File: builtin/sparse-checkout.c [hunk 10]
```diff
@@ -60,18 +65,53 @@ static int sparse_checkout_list(int argc, const char **argv)
...
+
+	memset(&o, 0, sizeof(o));
+	o.verbose_update = isatty(2);
+	o.merge = 1;
+	o.update = 1;
+	o.fn = oneway_merge;
+	o.head_idx = -1;
+	o.src_index = r->index;
+	o.dst_index = r->index;
+	o.skip_sparse_checkout = 0;
```
Comment (kewillford) [inline builtin/sparse-checkout.c]: How did you decide these were the right options for unpack_trees?

File: builtin/sparse-checkout.c [hunk 11]
```diff
@@ -343,11 +405,11 @@ static int sparse_checkout_set(int argc, const char **argv, const char *prefix)
 			while (!strbuf_getline(&line, stdin)) {
 				size_t len;
 				char *buf = strbuf_detach(&line, &len);
-				add_pattern(buf, buf, len, &pl, 0);
+				add_pattern(buf, empty_base, 0, &pl, 0);
```
Comment (kewillford) [inline builtin/sparse-checkout.c:450]: Will you explain this change for me?

File: builtin/sparse-checkout.c [hunk 12]
```diff
@@ -252,28 +298,45 @@ static void write_cone_to_file(FILE *fp, struct pattern_list *pl)
...
-	fp = fopen(sparse_filename, "w");
+	fd = hold_lock_file_for_update(&lk, sparse_filename,
+				      LOCK_DIE_ON_ERROR);
+
+	result = update_working_directory(pl);
+	if (result) {
+		rollback_lock_file(&lk);
+		free(sparse_filename);
+		clear_pattern_list(pl);
+		update_working_directory(NULL);
```
Comment (kewillford) [inline builtin/sparse-checkout.c:358]: Wouldn't we need to load the previous patterns and pass that to `update_working_directory`?

**Review by kewillford — COMMENTED** [review]
Questions to help me better understand.

File: dir.c (hunk 7 above)
Comment (derrickstolee) [reply dir.c:1298]: Unfortunately, `MATCHED_RECURSIVE` doesn't work if we return it for files.

File: dir.c (hunk 9 above)
Comment (derrickstolee) [reply dir.c:633]: The point is to say "all files will match". The place this comes in is `git sparse-checkout disable` with cone mode enabled. It needs to set the sparse-checkout file to "/*\n" and then update the working directory before removing the config. Without this fix, the cone-mode patterns would not work.

File: builtin/sparse-checkout.c (hunk 10 above)
Comment (derrickstolee) [reply builtin/sparse-checkout.c]: I read the code in `builtin/read-tree.c` and tracked what would happen in a call to `git read-tree -mu HEAD`.

File: builtin/sparse-checkout.c (hunk 11 above)
Comment (derrickstolee) [reply builtin/sparse-checkout.c:450]: Before, we were not using the `pattern_list` for anything other than tracking the patterns to set in the sparse-checkout file.

Now, we want to use the `pattern_list` in-memory to update the working directory.

The previous way I was calling `add_pattern()` was wrong and led to errors when using these patterns in-memory.

File: builtin/sparse-checkout.c (hunk 12 above)
Comment (derrickstolee) [reply builtin/sparse-checkout.c:358]: By using `NULL`, it will load the patterns from the `sparse-checkout` file in the normal way.

File: dir.c (hunk 8 above)
Comment (derrickstolee) [reply dir.c:628]: The order is absolutely important in the `sparse-checkout` file. In our typical cone-based patterns, we start with these two lines:

```
/*     # include all files
!/*/   # except those in folders
```

The order gives the meaning to the negation. The last pattern to match the file `/A/file.txt` is `!/*/`, so the sparse-checkout says "do not include this file". (If no pattern matches at all, the default is "do not include this file".)

If they are reversed:

```
!/*/     # do not include things in folders
/*       # include everything
```

then the sparse-checkout file will match everything, as the _last_ pattern to match is a positive pattern.

So, this code is saying "If I see `!/*/`, then set `full_cone` to zero. If I see `/*`, then set `full_cone` to true."

If there are other patterns that make this file not look like a cone-based file, then `use_cone_patterns` is set to zero and `full_cone` is ignored.

**Review by wilbaker — APPROVED** [review]
Looks good to me, but @kewillford is more of an expert on this code so you might want to wait for his approval before merging.

File: builtin/sparse-checkout.c [hunk 13]
```diff
@@ -60,18 +65,53 @@ static int sparse_checkout_list(int argc, const char **argv)
...
+	o.skip_sparse_checkout = 0;
+	o.pl = pl;
+	o.keep_pattern_list = !!pl;
+
+	resolve_undo_clear_index(r->index);
+	setup_work_tree();
+
+	cache_tree_free(&r->index->cache_tree);
+
+	repo_hold_locked_index(r, &lock_file, LOCK_DIE_ON_ERROR);
```
Comment (kewillford) [inline builtin/sparse-checkout.c]: I'm wondering if we should hold the `index.lock` for the entire `sparse-checkout` command to prevent races?  For example running a checkout after this code commits the `index.lock` but it runs before the sparse-checkout file was updated? 

Since commands get the index.lock before modifying the index, I'm thinking the sequence should be:
1. Get the `index.lock`
2. Get the `sparse-checkout.lock`
3. Update the working directory and sparse-checkout (I don't think order matters here since we have both locks)
4. Commit the `sparse-checkout`
5. Commit the `index`

Comment (derrickstolee) [reply builtin/sparse-checkout.c]: I'll give that a try, thanks!

**Review by kewillford — APPROVED** [review]
Looks good. Approved with the one suggestion about locking.

File: builtin/sparse-checkout.c (hunk 13 above)
Comment (derrickstolee) [reply builtin/sparse-checkout.c]: I rearranged the code to do exactly this in 5cd306f. Thanks!

File: builtin/sparse-checkout.c [hunk 14]
```diff
@@ -252,28 +327,53 @@ static void write_cone_to_file(FILE *fp, struct pattern_list *pl)
...
 	else
 		write_patterns_to_file(fp, pl);
 
-	fclose(fp);
-	free(sparse_filename);
+	fflush(fp);
 
+	/* commit index.lock file */
+	finish_update_data(ud);
+	free(ud);
```
Comment (kewillford) [inline builtin/sparse-checkout.c:376]: Should the commit of the `index.lock` be the last thing to happen so after the commit of the `sparse-checkout.lock`?  I'm not sure what git reads first the sparse-checkout file or the index.  Not sure it matters too much either since both renames should happen rather fast. But since the commit has
```
  5. Commit sparse-checkout.lock.
  6. Commit index.lock.
```
Thought I would ask.

Comment (derrickstolee) [reply builtin/sparse-checkout.c:376]: Since the `sparse-checkout` builtin is the only thing looking at `sparse-checkout.lock`, this won't affect parallel checkouts. A `checkout`-like command would take `index.lock` before reading the `sparse-checkout` file.

To avoid deadlocks between competing `git sparse-checkout set` commands, it is best to "pop" the locks in a stack.

Comment (derrickstolee) [reply builtin/sparse-checkout.c:376]: And yes, I definitely did them in the wrong order in the code. Thanks for catching that!
