### PR TITLE
virtualfilesystem: fix bug with symlinks being ignored

### LINKED ISSUE #25: Untracked symlinks not reported by 'git status' when virtualization hook in use
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.18.0.gvfs.1.26.gf61ade4ce8
cpu: x86_64
built from commit: 36c283e844cdcc1293983df635d0164cde010c2a
sizeof-long: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Windows 10 insider release and Mac 10.13.6
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD on Windows and Terminal on Mac.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
1. Clone repo with VFS for Git
2. Create a new symbolic link
3. Run git status
```
 - What did you expect to occur after running these commands?

Git status should report the new link as untracked.

 - What actually happened instead?

Status did not report the new link.

### PR DESCRIPTION
**Pull request by benpeart**
The virtual file system code incorrectly treated symlinks as directories
instead of regular files.  This meant symlinks were not included even if
they are listed in the list of files returned by the core.virtualFilesystem
hook proc.  Fixes #25

Signed-off-by: Ben Peart <Ben.Peart@microsoft.com>

### CODE REVIEW

File: virtualfilesystem.c [hunk 1]
```diff
@@ -227,7 +227,7 @@ int is_excluded_from_virtualfilesystem(const char *pathname, int pathlen, int dt
 		return ret;
 	}
 
-	if (dtype == DT_DIR || dtype == DT_LNK) {
```
Comment (kewillford) [inline virtualfilesystem.c]: Can a link be a directory or a file?  If the link can be a directory do we need to do something different?

Comment (benpeart) [reply virtualfilesystem.c]: The code in treat_one_path() (the normal git excludes logic replaced by the virtual file system hashmap based code) treats DT_REG and DT_LNK the same.  In addition, the comment in the code states "Nobody actually cares about the difference between DT_LNK and DT_REG" so I think we're ok.
