### PR TITLE
multi-pack-index: use real paths for --object-dir

### LINKED ISSUE #497: multi-pack-index expire doesn't do anything if --objects-dir contains backward slashes
VFSForGit runs `PackfileMaintenanceStep` periodically, but content of `pack` subdirectory in `.gvfsCache` remains unchanged.
The reason is that `git multi-pack-index expire` command doesn't work with backward slash paths for `--object-dir` (see reproduction example below).
So VFSForGit runs `expire` with backward slashes and it doesn't do anything.
It seems git behavior should not depend on paths format.

 - [x] I was not able to find an [open](https://github.com/microsoft/git/issues?q=is%3Aopen)
        or [closed](https://github.com/microsoft/git/issues?q=is%3Aclosed) issue matching
        what I'm seeing, including in [the `git-for-windows/git` tracker](https://github.com/git-for-windows/git/issues).

### Setup

 - Which version of `microsoft/git` are you using? Is it 32-bit or 64-bit?
```
git version 2.36.0.vfs.0.0
cpu: x86_64
built from commit: 5323cc6ccf2923f4f41da713ea9d1125704dec5b
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

Are you using Scalar or VFS for Git?

`VFS for Git`

If VFS for Git, then what version?

```
$ gvfs version

v1.0.21229.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1645]
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

no

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

If you run `multi-pack-index expire` with backward slashes for `--object-dir` command do nothing
```
c:\Windows>"C:\Program Files\Git\mingw64\bin\git.exe" --git-dir="F:\Projects\Monorepo\src\.git" -c core.virtualizeobjects=false multi-pack-index expire --object-dir="F:\.gvfsCache\d7745fd3f2f047bab6827f5b183fdbf0\gitObjects"
13:16:41.308775 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
13:16:41.310776 run-command.c:1549      run_processes_parallel: preparing to run up to 1 tasks
13:16:41.310776 run-command.c:654       trace: run_command: F:/Projects/Monorepo/src/.git/hooks/pre-command.exe multi-pack-index expire '--object-dir=F:\.gvfsCache\d7745fd3f2f047bab6827f5b183fdbf0\gitObjects' --git-pid=31564
13:16:41.404016 run-command.c:1581      run_processes_parallel: done
13:16:41.404016 git.c:531               trace: built-in: git multi-pack-index expire '--object-dir=F:\.gvfsCache\d7745fd3f2f047bab6827f5b183fdbf0\gitObjects'
13:16:41.410589 run-command.c:1549      run_processes_parallel: preparing to run up to 1 tasks
13:16:41.410589 run-command.c:654       trace: run_command: F:/Projects/Monorepo/src/.git/hooks/post-command.exe multi-pack-index expire '--object-dir=F:\.gvfsCache\d7745fd3f2f047bab6827f5b183fdbf0\gitObjects' --git-pid=31564 --exit_code=0
13:16:41.497558 run-command.c:1581      run_processes_parallel: done
```

Command starts doing smth with forward slashes for `--object-dir`:
```
c:\Windows>"C:\Program Files\Git\mingw64\bin\git.exe" --git-dir="F:\Projects\Monorepo\src\.git" -c core.virtualizeobjects=false multi-pack-index expire --object-dir="F:/.gvfsCache/d7745fd3f2f047bab6827f5b183fdbf0/gitObjects"
13:16:56.612496 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
13:16:56.615528 run-command.c:1549      run_processes_parallel: preparing to run up to 1 tasks
13:16:56.615528 run-command.c:654       trace: run_command: F:/Projects/Monorepo/src/.git/hooks/pre-command.exe multi-pack-index expire --object-dir=F:/.gvfsCache/d7745fd3f2f047bab6827f5b183fdbf0/gitObjects --git-pid=34208
13:16:56.715399 run-command.c:1581      run_processes_parallel: done
13:16:56.715399 git.c:531               trace: built-in: git multi-pack-index expire --object-dir=F:/.gvfsCache/d7745fd3f2f047bab6827f5b183fdbf0/gitObjects
Unlink of file 'F:/.gvfsCache/d7745fd3f2f047bab6827f5b183fdbf0/gitObjects/pack/from-loose-922b0b1f773d613ed0ae0a493433d10461ae7c4f.idx' failed. Should I try again? (y/n)
```

 - If the problem was occurring with a specific repository, can you specify
   the repository?

   * [ ] Public repo: **insert URL here**
   * [ ] Windows monorepo
   * [ ] Office monorepo
   * [ ] Other Microsoft-internal repo: **insert name here**
   * [x] Other internal repo.

### PR DESCRIPTION
**Pull request by derrickstolee**
This resolves #497.

Looking at this, it seems that VFS for Git users have not been getting all of the benefits of background maintenance for quite some time. This will probably justify a `v2.36.0.vfs.0.1` release for those users. We should wait for upstream feedback, first. I will prepare an upstream patch soon.

### CODE REVIEW

File: builtin/multi-pack-index.c [hunk 1]
```diff
@@ -127,6 +135,8 @@ static int cmd_multi_pack_index_write(int argc, const char **argv)
 
 	FREE_AND_NULL(options);
 
+	normalize_object_dir();
```
Comment (vdye) [inline builtin/multi-pack-index.c]: Rather than calling this in each subcommand, you can _possibly_ do it with `OPT_CALLBACK`:

```
static struct option common_opts[] = {
	OPT_CALLBACK(0, "object-dir", &opts.object_dir, N_("file"),
		     N_("object directory containing set of packfile and pack-index pairs"),
		     normalize_object_dir),
	OPT_END(),
};
```

The function signature of `normalize_object_dir` would need to change to:

```
static int normalize_object_dir(const struct option *opt, const char *arg, int unset)
```

...and you might need to copy some of the filename processing from `parse-options.c:get_value()` ([link](https://github.com/microsoft/git/blob/vfs-2.36.0/parse-options.c#L170-L181)), but it would centralize the processing and avoid needing to make sure we have `normalize_object_dir` in every new subcommand.

**Review by vdye — COMMENTED** [review]
I made a (hopefully straightforward? and hopefully workable?) suggestion for how you might be able to centralize the call to `normalize_object_dir`, but otherwise this functionally looks correct.

File: builtin/multi-pack-index.c (hunk 1 above)
Comment (derrickstolee) [reply builtin/multi-pack-index.c]: Great idea! That's much cleaner. The initialization to the `.git/objects` directory can happen before parsing.

I've got this sent upstream, too. Do you want to add that suggestion there, too?

**Comment by derrickstolee** [comment]
@vdye: this made it to `next` upstream. Could you re-review this version so we have it in case of a minor release?

**Review by vdye — APPROVED** [review]
🚀
