### PR TITLE
virtualfilesystem: don't run the virtual file system hook if the index has been redirected

### LINKED ISSUE #13: `git difftool -d` with Beyond Compare 4: cannot spawn .git/hooks/virtual-filesystem: No such file or directory
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit
```
$ git --version --build-options

git version 2.17.1.gvfs.2.1.6.gdc051a1
cpu: x86_64
built from commit: dc051a1f5beb8ce0b22051afd9be86a0541a534a
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

64-bit Windows 10

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

M:\>type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

This is with a VFSForGit repo.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
<modify some files>
git difftool -d
```
 - What did you expect to occur after running these commands?

Beyond Compare 4 would launch, and allow me to modify and save source files.

 - What actually happened instead?

Beyond Compare 4 launched, but changes made in the right pane were lost (and the error message below was displayed).

```
M:\gvfsDiffTest2\src>git difftool -d
error: cannot spawn .git/hooks/virtual-filesystem: No such file or directory
fatal: unable to load virtual file system
fatal: diff-files did not exit properly
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This is not repo specific, but is specific to using VFSForGit.

### PR DESCRIPTION
**Pull request by benpeart**
Closes #13

Some git commands spawn helpers and redirect the index to a different
location.  These include "difftool -d" and the sequencer
(i.e. `git rebase -i`, `git cherry-pick` and `git revert`) and others.
In those instances we don't want to update their temporary index with
our virtualization data.

Helped-by: Johannes Schindelin <johannes.schindelin@gmx.de>
Signed-off-by: Ben Peart <Ben.Peart@microsoft.com>

### CODE REVIEW

File: config.c [hunk 1]
```diff
@@ -2316,10 +2316,23 @@ int git_config_get_virtualfilesystem(void)
...
+		 */
+		char *default_index_file = xstrfmt("%s/%s", the_repository->gitdir, "index");
+		int should_run_hook = !strcmp(default_index_file, the_repository->index_file);
+
+		free(default_index_file);
+		if (should_run_hook) {
+			/* virtual file system relies on the sparse checkout logic so force it on */
+			core_apply_sparse_checkout = 1;
+			return 1;
+		}
```
Comment (kewillford) [inline config.c]: Do we need to turn off the `core_virtualfilesystem` flag in an else here or are all the checks of that flag inside a check of `core_apply_sparse_checkout`?  Because not it looks like we are in a state where the one is set but the other isn't.

Comment (benpeart) [reply config.c]: Good catch.  Yes, I'll update it to ensure they stay consistent.
