### PR TITLE
deserialize-status: silently fallback if we cannot read cache file

### LINKED ISSUE #126: git status should not fail when it is unable to open cache file
In Microsoft/VFSForGit#663, a functional test failed to run status because git encountered an error (access denied) when reading from a status cache file.

Reading status from a cache file is a best effort operation. If the file does not exist, we fall back to computing a fresh status. The intention is that failing to read from the cache file is also a best effort, and we should not terminate if we are unable to read an existing file.

We should be more resilient to these types of errors, and fallback to computing full status gracefully rather than terminating. The issue here is the utility `xopen` function used by status cache deserialization logic will terminate if it encounters an issue reading the file.

### PR DESCRIPTION
**Pull request by jeffhostetler**
Teach Git to not throw a fatal error when an explicitly-specified
status-cache file (`git status --deserialize=<foo>`) could not be
found or opened for reading and silently fallback to a traditional
scan.

This matches the behavior when the status-cache file is implicitly
given via a config setting.

Signed-off-by: Jeff Hostetler <jeffhost@microsoft.com>

### CODE REVIEW

File: builtin/commit.c [hunk 1]
```diff
@@ -211,12 +211,18 @@ static int opt_parse_deserialize(const struct option *opt, const char *arg, int
...
-		if (deserialize_path && *deserialize_path
-		    && (wt_status_deserialize_access(deserialize_path, R_OK) != 0))
-			die("cannot find serialization file '%s'",
-			    deserialize_path);
-
-		do_explicit_deserialize = 1;
+		if (!deserialize_path || !*deserialize_path)
+			do_explicit_deserialize = 1; /* read stdin */
+		else if (wt_status_deserialize_access(deserialize_path, R_OK) == 0)
+			do_explicit_deserialize = 1; /* can read from this file */
```
Comment (derrickstolee) [inline builtin/commit.c:217]: the fact that these two variables are the same made me wonder if this is the right approach, but you seem to test both cases.

**Review by derrickstolee — APPROVED** [review]
I don't fully understand the difference between `do_explicit_deserialize` and `do_implicit_deserialize`, but your tests look sufficient. Please just take a quick look at my comment to see if there is an issue or not.

File: builtin/commit.c (hunk 1 above)
Comment (jeffhostetler) [reply builtin/commit.c:217]: Naming things is hard.

The variable `do_implicit...` handles the case where we inherited a config setting.  This was something that the gvfs installer set up and is usually outside of the user's view.

The `do_explicit...` variable handles the `--deserialize[=<path>]` command line option, which overrides the config setting.  IIRC this was added later.

The original design was that if the path from the config was not found, silently ignore it and go on and do a scan -- since that would happen any time the gvfs service was having problems, for example, and the user wouldn't know why status was broken and they were getting an obscure error message.

But when given on the command line, usual practice is to complain if an input is not found.
But that hard error threw Jameson's test/expectations.

Hence the 2 different code paths in the original code for determining whether we can read the status-cache and whether to complain about it.

Structurally, the actual code change is a lot smaller than it looks, but I refactored it a bit for (hopefully) clarity.  Perhaps I should have written it as:

    if (path && *path && access(...)) {
        do_implicit = 0
        do_explicit = 0
        return 0
    }
